name: Update Subscription


on:

  schedule:

    - cron: "0 */6 * * *"


  workflow_dispatch:



permissions:

  contents: write



jobs:


  build:


    runs-on: ubuntu-latest



    steps:



      # =====================
      # 拉取代码
      # =====================

      - name: Checkout

        uses: actions/checkout@v4

        with:

          fetch-depth: 0





      # =====================
      # Python环境
      # =====================

      - name: Setup Python

        uses: actions/setup-python@v5

        with:

          python-version: "3.12"





      # =====================
      # 安装依赖
      # =====================

      - name: Install requirements

        run: |

          python -m pip install --upgrade pip

          pip install -r requirements.txt





      # =====================
      # 清理旧文件
      # =====================

      - name: Clean old files

        run: |

         rm -rf __pycache__

         rm -f *.pyc

         rm -f xray.log

         rm -f xray_error.log
 
         rm -f xray_test.json
 
         rm -f output/status.json
 




      # =====================
      # 运行生成器
      # =====================

      - name: Run generator

        run: |

          python main.py





      # =====================
      # 检查结果
      # =====================

      - name: Check result

        run: |

          echo "========== OUTPUT =========="

          ls -lh output || true


          echo "========== DATABASE =========="

          ls -lh database.db || true


          echo "========== STATUS =========="

          cat output/status.json || true





      # =====================
      # 保存结果
      # =====================

      - name: Save result

        run: |


          git config user.name "github-actions"


          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"



          git add output/ database.db



          if git diff --cached --quiet;

          then

              echo "No changes"

          else

              git commit -m "auto update"

              git push origin main

          fi
